version: "3.8"
volumes:
  php-fpm-socket:
  db-store:
services:
  app:
    build: ./infra/docker/php
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ../beginner-lessons/beginner-lesson1:/work/backend

  web:
    build: ./infra/docker/nginx
    ports:
      - 8080:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ../beginner-lessons/beginner-lesson1:/work/backend

  db:
    build: ./infra/docker/mysql
    ports:
      - 13306:3306
    volumes:
      - db-store:/var/lib/mysql
